name: axiestudio
services:
- name: axiestudio-app
  source_dir: /
  github:
    repo: OGGsd/properaxiestudio
    branch: main
    deploy_on_push: true
  run_command: axiestudio run --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 7860
  routes:
  - path: /
  envs:
  - key: DO_NOT_TRACK
    value: "true"
  - key: AXIESTUDIO_SECRET_KEY
    value: R2Rlc3FqTXpxWWVkUlMwU1Nxc2xxT1dZUzE0T2xPZ1VsbDJUalRpZHM=
  - key: AXIESTUDIO_AUTO_LOGIN
    value: "False"
  - key: AXIESTUDIO_SUPERUSER
    value: stefan@axiestudio.se
  - key: AXIESTUDIO_SUPERUSER_PASSWORD
    value: STEfanjohn!12
  - key: AXIESTUDIO_NEW_USER_IS_ACTIVE
    value: "True"
  - key: DATABASE_URL
    value: postgresql://db:AVNS_9f4U8riTaUYdwqimQRC@app-57f1a664-8c39-4f05-99bf-bcf5f51c182a-do-user-24001760-0.h.db.ondigitalocean.com:25060/db?sslmode=require
  - key: AXIESTUDIO_HOST
    value: "0.0.0.0"
  - key: AXIESTUDIO_PORT
    value: "7860"
  - key: PORT
    value: "7860"
  - key: AXIESTUDIO_CACHE_TYPE
    value: "simple"
  - key: AXIESTUDIO_LOG_LEVEL
    value: "info"
  - key: AXIESTUDIO_WORKERS
    value: "1"


